name: frontend-check-trivy-image
description: 'frontend-check-trivy-image'
inputs:
    docker-username:
        description: docker-username
        required: true
    github-sha:
        description: github-sha
        required: true
runs:
    using: 'composite'
    steps:
        - name: build image
          shell: bash
          run: |
              docker build -t ${{ inputs.docker-username }}/homepage:sha-${{ inputs.github-sha }} .
        - name: trivy image scan
          uses: aquasecurity/trivy-action@master
          with:
              image-ref: '${{ inputs.docker-username }}/homepage:sha-${{ inputs.github-sha }}'
              format: 'sarif'
              output: 'trivy-image-results.sarif'
              ignore-unfixed: true
        - name: upload trivy image scan results to GitHub security tab
          uses: github/codeql-action/upload-sarif@v2
          with:
              sarif_file: 'trivy-image-results.sarif'
              category: 'image'
