name: frontend-build-and-test
description: 'frontend-build-and-test'
inputs:
  frontend-directory:
    description: Frontend directory from project root
    required: true
runs:
  using: 'composite'
  steps:
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: '20.9.0'
        cache: 'npm'
        cache-dependency-path: ${{ inputs.frontend-directory }}/package-lock.json

    - name: npm ci
      shell: bash
      working-directory: ${{ inputs.frontend-directory }}
      run: npm ci

    #- name: npm run test
    #  shell: bash
    #  working-directory: ${{ inputs.frontend-directory }}
    #  run: npm run test:unit

    - name: npm run build
      shell: bash
      working-directory: ${{ inputs.frontend-directory }}
      run: CI=true npm run build

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      shell: bash
    - name: Start application
      run: npm run dev & sleep 5
      shell: bash
    - name: Run Playwright tests
      run: npm run e2e
      shell: bash
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
