name: main-build-test-release

on:
  push:
    branches:
      - main

jobs:
  frontend-build-and-test:
    runs-on: ubuntu-latest
    environment: oskar-westmeijer-environment
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/frontend-build-and-test
        with:
          frontend-directory: .

  codeql-check:
    uses: ./.github/workflows/codeql.yml
    permissions:
      actions: read
      contents: read
      security-events: write

  frontend-check-trivy-image:
    runs-on: ubuntu-latest
    needs: [frontend-build-and-test]
    environment: oskar-westmeijer-environment
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/frontend-check-trivy-image
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          github-sha: ${{ github.sha }}

  release-frontend-docker-image:
    needs: [frontend-build-and-test]
    runs-on: ubuntu-latest
    environment: oskar-westmeijer-environment
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: image tagging
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/homepage
          tags: |
            # set latest tag for master branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=sha,format=long
      - name: build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
